Algoritmo "Concatenação idade"

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anderson Lira da Silva
// Data atual  : 01/03/2021
Var
   // Seção de Declarações das variáveis

   nome:caractere
   idade: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o nome")
   leia(nome)
   escreval("Digite a idade")
   leia(idade)

   escreval(nome, " tem: ", idade, " anos de idade")


Fimalgoritmo