Algoritmo "Meu primeiro algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Aluno       : Anderson Lira da Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anderson Lira da Silva
// Data atual  : 24/02/2021
Var
Var
   // Seção de Declarações das variáveis
       nota: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   nota <- 100
   escreva("Resultado:", nota)

Fimalgoritmo