Algoritmo "Operadores Relacionais"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anderson Lira da Silva
// Data atual  : 01/03/2021
Var
   // Seção de Declarações das variáveis
   nota01, nota02: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   nota01 :=10
   nota02 := 15
   se (nota01 <> nota02) entao
      escreval("Nota01 é diferente")
   senao
      escreval("Nota01 é igual")
   fimse

Fimalgoritmo