Algoritmo "Variaveis"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Aluno       : Anderson Lira da Silva
// Descrição   : Saber Variaveis
// Autor(a)    : Anderson Lira da Silva
// Data atual  : 24/02/2021
Var
   // Seção de Declarações das variáveis
   primeiroNome, segundoNome, cidade, endereco:caractere
   idade: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo